### ISSUE TITLE
Deleting a Group?

### ISSUE THREAD

**Issue by smithgb** [veevickytoria/Section04#101]
I'm trying to delete a group and it says the group id doesn't exist, but I'm able to retrieve the info for that group. Pictures below:

![screen shot 2014-02-07 at 5 09 30 pm](https://f.cloud.github.com/assets/5507787/2114882/0013772e-9045-11e3-8a8b-4492f16f11bb.png)

![screen shot 2014-02-07 at 5 10 08 pm](https://f.cloud.github.com/assets/5507787/2114885/05e14050-9045-11e3-9c2c-fcaa95e958f4.png)

**Comment by Paulbliudzius** [comment]
Sorry about the inconvenience. This has been resolved.
