### ISSUE TITLE
Meetings not working

### ISSUE THREAD

**Issue by WillBrophy** [veevickytoria/Section04#104]
the meeting calls dont seem to be working anymore. got the following error:

 Parse error: syntax error, unexpected '[', expecting ')' in C:\wamp\www\Meeting.php on line 253

**Comment by smithgb** [comment]
Getting that same thing on the website too.
![capture](https://f.cloud.github.com/assets/5507787/2178643/e1531906-9671-11e3-8782-e0b9fcb6657b.PNG)

**Comment by shahdk** [comment]
Same for iOS as well.

**Comment by Paulbliudzius** [comment]
Could you try now and let me know?

**Comment by smithgb** [comment]
Works.

**Comment by WillBrophy** [comment]
works! thanks
