### ISSUE TITLE
No node updated - project

### ISSUE THREAD

**Issue by WillBrophy** [veevickytoria/Section04#105]
When trying to update the memebrs in a group, it simply returns "No node updated" and does not update the project. Here is the put request:
{"projectID":"8789", "field":"members", "value":[{"userID":"5623"}]}

**Comment by Paulbliudzius** [comment]
Looking into it.

**Comment by Paulbliudzius** [comment]
Fixed, it was set as a field users instead of members which got really confusing in the API then.
It has been switched to 'members', like your put now to have consistency.
