### ISSUE TITLE
UserSettings

### ISSUE THREAD

**Issue by earlesja** [veevickytoria/Section04#106]
The PHP page for this feature doesn't even exist.

<a href="http://imgur.com/g6NwEyF"><img src="http://i.imgur.com/g6NwEyF.png" title="Hosted by imgur.com" /></a>

**Comment by schwalbs** [comment]
What was the call? I have a feeling the .htaccess wasn't update. We tried having usersettings in a separate file, but ended up integrating it with User.php

**Comment by schwalbs** [comment]
I'll take a look at this

**Comment by gamescoot** [comment]
I fixed it... Just a small problem in the php files. Sorry about the inconvenience. I did have it done last week, but I was testing on my local machine. Again. I apologize.
