### ISSUE TITLE
Project Background, Executive Summary etc

### ISSUE THREAD

**Issue by shahdk** [veevickytoria/Section04#39]
Project Background + Functionality Not in Use Cases (10 Points)

**Comment by shahdk** [comment]
due 10/24

**Comment by shahdk** [comment]
Also includes Index and References

**Comment by shahdk** [comment]
also includes Design Contraints, Hardware and Software Interfaces, and the Documentation, Installation etc requirements.

**Comment by mccormjt** [comment]
done - MS3 was turned in
