### ISSUE TITLE
PUT Requests for Tasks

### ISSUE THREAD

**Issue by shomerrt** [veevickytoria/Section04#81]
Similar issue as the POST request.  The user effectively gets assigned himself as a task.  Perhaps the nodes are switched as well just like in the POST issue?

**Comment by schwalbs** [comment]
I'll take a look at that tonight

**Comment by schwalbs** [comment]
@shomerrt I think I fixed the issue, or at least it seems to be working from my local version. Give it a try again and let me know

**Comment by gamescoot** [comment]
I'm closing this issue, feel free to reopen with any questions
