### ISSUE TITLE
GET MeetingInfo

### ISSUE THREAD

**Issue by OneCricketeer** [veevickytoria/Section04#82]
Once Agenda is properly working, can the appropriate meeting node have a key for the agenda that is attached to it as well?

**Comment by OneCricketeer** [comment]
Also, is there a specific dateTime format everyone should be using? I know everything is strings, but parsing on our ends is an issue if there is no standard... From the API I see "Monday, 16-Aug-15 20:59:59 UTC" which if I convert that to a dateformat, I get "EEEE, dd-MMM-yy HH:mm:ss zzz"

**Comment by smithgb** [comment]
For date time, I'm thinking the backend should store it as some sort of universal format like they have now and then the front ends can manipulate it how they want for display, but any dates we send to the backend should be in the standard form they're using.

**Comment by OneCricketeer** [comment]
I completely agree, they said they expect the default javascript format, but I haven't been able to find anywhere that specifically states a universal format other than [ISO8601](http://www.hackcraft.net/web/datetime/#iso8601)

**Comment by schwalbs** [comment]
Sorry for not responding earlier, busy schedules and career fair prep. Anyway, your original request is definitely possible, and we'll try to get that implemented as soon as Agenda is done.  Right now we just take in what you send us, so we don't have a format.  How easy is it to send timestamps from the front ends? That way you guys could present it anyway you want.

**Comment by smithgb** [comment]
We can probably just use a javascript function and attach it to the request data.

**Comment by OneCricketeer** [comment]
As a sidenote to this, the actual call has userID of the creator as a key instead of the meetingID. The API shows it as meetingID. 
I think the milliSecs approach, or [Unix time](https://en.wikipedia.org/wiki/Unix_time) is the easiest to get, parse as we please, then convert back and send. I found these libraries/methods for everyone's use.  
JavaScript: [Moment.js](http://momentjs.com/)
iOS: [Built-in way](http://stackoverflow.com/a/5335105)
Android: [JodaTime](http://www.joda.org/joda-time/)

**Comment by OneCricketeer** [comment]
@dgart01 Line 27 of Meeting.php, why is it userID and not meetingID?

**Comment by gamescoot** [comment]
This is the POST method for meeting. According to the API, create meeting uses userID. The meetingID for the node wouldn't even exist yet because the node doesn't exist.

**Comment by schwalbs** [comment]
Following up on what Scott said, the ID for each node is something the database assigns when the node is created ($client->makeNode() in the code), it isn't something we assign. Does that answer your question

**Comment by OneCricketeer** [comment]
Ah, my bad, I see it is POST now. I was wondered why the GET method returns userID instead of meetingID. I know I need the meeting ID anyway to even GET meeting info, but I was curious

**Comment by gamescoot** [comment]
I'm closing this issue. Feel free to reopen it with any questions
