### ISSUE TITLE
Assigning users to task

### ISSUE THREAD

**Issue by WillBrophy** [veevickytoria/Section04#83]
Should a task be able to have more than one user assigned to it? and should a group also be able to be assigned to it?

**Comment by schwalbs** [comment]
@WillBrophy Right now, we don't support multiple users being assigned to a task, and we only allow users to be assigned to tasks. That's how we understood the features document from way back when, but if all front-ends want support for these features, we might be able to implement it.

**Comment by smithgb** [comment]
If that's what you got from the requirements doc then just go with it. I think it makes less sense for a group to be assigned a task than it does for a group to be invited to a meeting/project. Web team is fine with the way you have it.
