### ISSUE TITLE
User Settings?

### ISSUE THREAD

**Issue by smithgb** [veevickytoria/Section04#91]
The web team would like there to be a way for users to define personal settings that can be stored in the backend. Details of what settings to include can be discussed later.

**Comment by shahdk** [comment]
Currently for iOS settings, we allow user to change email, change password, turn notifications on or off, and set when they want to be notified. For iOS, we used the deafult options like on time of event, 15 min before, 30 min before, 1 hour before, 2 hours before, 1 day before, 2 days before.

So for user Settings, I think backend should only have userID, are the notifications turned on or off, and what option did the user pick.

We would also need to set a global set of options for when the users want to be notified.

**Comment by smithgb** [comment]
Is this going to be completed?

**Comment by gamescoot** [comment]
Yup. Prolly today. Definitely by thursday. Get hyped! :D

**Comment by smithgb** [comment]
Cool. Could the specifications be posted somewhere so we could write code for it? We'll wait until you have it implemented to test ours.

**Comment by gamescoot** [comment]
Actually, I had trouble writing it, because I don't know everything needed for the settings. I want to implement it right the first time, so I'll ask the class everything they need for settings now that we know for sure that we're implementing it.

**Comment by smithgb** [comment]
I see the API spreadsheet has been updated to include methods for user settings. Thanks! Issue closed.
