### ISSUE TITLE
GET User Meetings error

### ISSUE THREAD

**Issue by OneCricketeer** [veevickytoria/Section04#92]
5848 is a valid userID. [Server Response](http://csse371-04.csse.rose-hulman.edu/User/5848)

``` json
{
title: "",
phone: "",
location: "",
email: "ninja@user.com",
company: "",
name: "Yoyo"
}
```

When I do GET Meetings, I get this [Server Response](http://csse371-04.csse.rose-hulman.edu/User/Meetings/5848)

``` json
{
errorID: "11",
errorMessage: "5868 is an not a Meeting or Task node."
}
```

**Comment by gamescoot** [comment]
That is the correct info for 5848. It's actually stored like that. It's not an error. As for get meeting, I'm confused too.

**Comment by OneCricketeer** [comment]
It does work with other users, like 3495

``` json
{
meetings: [
{
id: 3495,
title: "Student",
type: "MADE_MEETING"
}
]
}
```

**Comment by gamescoot** [comment]
Fixed
