### ISSUE TITLE
deleteSpecificContact doesn't seem to work

### ISSUE THREAD

**Issue by mathbum** [veevickytoria/Section04#95]
when i used http://csse371-04.csse.rose-hulman.edu/Contact/Relation/26915
in my rest client google chrome app i got back 

Method Not Allowed

The requested method DELETE is not allowed for the URL /Contact/Relation/26915.

**Comment by millerns** [comment]
Oh, that's my mistake. I had the API wrong. "Relation" should be "Relations". I updated the API appropriately. Let me know if that fixes the problem.

**Comment by millerns** [comment]
Matt confirmed with me in person that this bug has been fixed.
