### ISSUE TITLE
Backend explanation please

### ISSUE THREAD

**Issue by OneCricketeer** [veevickytoria/Section04#99]
Is there a simple explanation why, for example, getUserMeetings, only returns the following instead of a full list of meetings?

``` json
{
  "meetings":[
  {
    "id":"@meetingID",
    "title":"@meetingTitle",
    "type":"@relationtype"}
  ]
}
```

The API for the getSchedule looks much more reasonable with the content of the meetings and task information.  

I know you can't have nested arrays in Neo4j, which you would have if you did: 

``` json
{
  "meetings" : [
  {  
    "userID":"@userID",
    "title":"@meetingTitle", 
    "location":"O257", 
     "description":"@meetingDescription",
     "endDatetime":"@dateTime", 
     "datetime":"@dateTime",
     "attendance":  [
        {"userID":"@userID"}, 
        {"userID":"@userID"}
      ]
  }
  ]
}
```

But in terms of performance and load on the server, I would suggest a possible refactoring would be having an attendance node to hold the list and a getAttendance call for only when the client needs it, that way N+1 network calls do not need to be made to get the information for N meetings. Only 1 needs to be made for all the general information about the meeting, then if we want the attendance, say when we view the meeting, then we can get the attendance.
I imagine a call like this: 
GET @ /Meeting/1234/Attendance

``` json
{
  "attendance":  [
    {"userID":"@userID"}, 
    {"userID":"@userID"}
  ]
}
```

**Comment by smithgb** [comment]
I agree. From the perspective of the front-end, it weighs down our application (bloats our code) much more when we have to make multiple calls to retrieve info for a single entity. I understand the goal of the design was to reduce the load on the server, but in reality a server is the foundation of an application and has much more power than a user's device. Also, we are trafficking incredibly, measly amounts of data in our project. Ruby on Rails intentionally constructs web pages as much as possible on the server before the client receives it so the browser ONLY has to make 1 request. Requiring the user to make several requests to do one task is wasteful. It is, however, probably too late to fix this.
